name: Auto refresh source
on:
  schedule:
    - cron: "0 16 */1 * *"
  push:
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt‑get update
          sudo apt‑get install‑y ca‑certificates
      - name: Run script
        run: python3 merge.py
      - name: Push changes
        run: |
          git config --global user.name "robot"
          git config --global user.email "robot@no.com"
          git add tv.json
          git commit -m "auto update" || true
          git push
